### ISSUE TITLE
How to do negative sampling

### ISSUE THREAD

**Issue by csypeng** [lemmonation/spine#1]
From Models.py Lines 267, 292 and main.py Line 168, I see the "labels" argument for the negative sampling is set to be a placeholder and needed to be specified by the user? If so, what is that used in the paper "Spine: structural identity preserved inductive network embedding"? Thank you.

**Comment by lemmonation** [comment]
You can find corresponding codes in minibatch.next_minibatch_feed_dict(), which describes the rpr sampling method for training pairs.
